### ISSUE TITLE
Return the password field instead of entire JSON response?

### ISSUE THREAD

**Issue by alankan-finocomp** [ansd/secrets-store-csi-driver-provider-lastpass#1]
Great motivation :+1: Every vault deserves a provider implementation one day :stuck_out_tongue_winking_eye: I got a suggestion/feedback though.

When it finds the matched item/account/password record from LastPass, it returns the entire JSON response in the `mount()` function. e.g.
```json
{"ID":"xxxxxx","Name":"fooPassword","Username":"","Password":"bar","URL":"http://","Group":"Terraform","Share":"Shared-Foo","Notes":"","LastModifiedGMT":"1663723046","LastTouch":"1663673430"}
```

https://github.com/ansd/secrets-store-csi-driver-provider-lastpass/blob/4dd3caa4b258f388199b7a3c7b1e43f919d1a871/server/server.go#L156-L163

Should we extract the `Password` field or should we support "extraction" in SecretProviderClass's parameters?

**Comment by ansd** [comment]
Thank you @alankan-finocomp.

My original thought was that applications can just parse the JSON an extract whatever information they want from the LastPass item / account.

I added a parameter to the SecretProviderClass which allows to only output the password.
See example in https://github.com/ansd/secrets-store-csi-driver-provider-lastpass/blob/26c98210ada707bb17e4cf296921977e1bdd4162/examples/secret-provider-class.yml#L35

Does this work for you?

**Comment by alankan-finocomp** [comment]
Thank you very much for the enhancement. Will test it out for my use case this week :bow:

**Comment by alankan-finocomp** [comment]
It works like a charm. Thank you very much :bow: I like that it allows us to design the pods universally to expect only the password in a vault-vendor-agnostic way :+1:

**Comment by ansd** [comment]
Thank you for testing it out @alankan-finocomp :)
